CREATE ROLE db_admin
	NOSUPERUSER
	INHERIT
	NOCREATEDB
	NOCREATEROLE
	NOREPLICATION;
CREATE ROLE data_writer
	NOSUPERUSER
	INHERIT
	NOCREATEDB
	NOCREATEROLE
	NOREPLICATION;

CREATE ROLE zeppelin_admin
	LOGIN
	PASSWORD 'zeppelin_admin'
	NOSUPERUSER
	INHERIT
	NOCREATEDB
	NOCREATEROLE
	NOREPLICATION;
GRANT db_admin TO zeppelin_admin;

CREATE ROLE zeppelin_user
	LOGIN
	PASSWORD 'zeppelin_user'
	NOSUPERUSER
	INHERIT
	NOCREATEDB
	NOCREATEROLE
	NOREPLICATION;
GRANT data_writer TO zeppelin_user;

COMMENT ON ROLE zeppelin_user IS 'Zeppelin application';
